global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using EasyTidy.Common;
global using EasyTidy.ViewModels;
global using EasyTidy.Views;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.UI;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Navigation;
global using WinUICommunity;
global using static EasyTidy.Common.AppHelper;
global using System;
