// -----------------------------------------------------------------------------------------------------
// | <auto-generated>                                                                                  |
// |    This code was generated by a tool.                                                             |
// |                                                                                                   |
// |    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. |
// | </auto-generated>                                                                                 |
// -----------------------------------------------------------------------------------------------------

// Define JSON file path variable for easy adjustment

namespace EasyTidy;
public partial class NavigationPageMappings
{
    public static Dictionary<string, Type> PageDictionary { get; } = new Dictionary<string, Type>
    {
        {"EasyTidy.Views.GeneralPage", typeof(EasyTidy.Views.GeneralPage)},
        {"EasyTidy.Views.FiltersPage", typeof(EasyTidy.Views.FiltersPage)},
        {"EasyTidy.Views.TaskOrchestrationPage", typeof(EasyTidy.Views.TaskOrchestrationPage)},
        {"EasyTidy.Views.AutomaticPage", typeof(EasyTidy.Views.AutomaticPage)},
    };
}
