
[[settings]]
source_path = ""
days_ago = 3
execution_mode = "once"
execution_interval = 60

[[settings.target_folders]]
target_folder = "D:/Backup/Documents"
file_types = ["txt", "xlsx", "docx"]

[[settings.target_folders]]
target_folder = "D:/Backup/Videos"
file_types = ["mp4", "avi"]

[[settings]]
source_path = ""
days_ago = 5
execution_mode = "monitor"
execution_interval = 120

[[settings.target_folders]]
target_folder = "D:/Backup/Pictures"
file_types = ["jpg", "png", "gif"]

[[settings.target_folders]]
target_folder = "D:/Backup/Music"
file_types = ["mp3", "wav"]
